import { StyleSheet } from "react-native";

export default StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    flex: 1,
    position: "absolute",
    marginTop: 5,
    backgroundColor: "white",
    borderRadius: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "100%",
    height: "100%",
    top: "13%",
  },
  input: {
    height: 40,
    margin: 12,
    borderRadius: 10,
    width: 300,
  },
  modalContent: {
    flex: 1,
    justifyContent: "center",
    margin: "5%",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    bottom: "80%",
    left: 0,
    right: 0,
    backgroundColor: "rgba(182,227,163,0.5)",
  },
  buttonSubmit: {
    borderRadius: 50,
    width: 180,
    height: 45,
    backgroundColor: "rgba(182,227,163,1)",
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  buttonCancel: {
    borderRadius: 50,
    width: 180,
    height: 45,
    backgroundColor: "lightcoral",
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  buttonView: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: "1%",
    justifyContent: "space-around",
    alignItems: "center",
    bottom: "60%",
    position: "absolute",
  },
});
