import { StyleSheet } from "react-native";

export default StyleSheet.create({
  //   containerMain: {
  //     flex: 1,
  //     alignItems: "center",
  //     justifyContent: "center",
  //     marginTop: 22,
  //   },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    flex: 1,
    position: "absolute",
    marginTop: 5,
    backgroundColor: "white",
    borderRadius: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "100%",
    height: "100%",
    top: "15%",
  },
  input: {
    height: 40,
    margin: 12,
    borderRadius: 10,
    width: 300,
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalContent: {
    flex: 1,
    justifyContent: "center",
    margin: "5%",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    bottom: "80%",
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0)",
  },
  button: {
    borderRadius: 50,
    width: 180,
    height: 45,
    backgroundColor: "skyblue",
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  buttonView: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 50,
    justifyContent: "space-around",
    alignItems: "center",
    bottom: "45%",
    position: "absolute",
  },
});
