import { StyleSheet } from "react-native";

export default StyleSheet.create({
  image: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
  },
  button: {
    borderRadius: 50,
    width: 180,
    height: 45,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  buttonFacebook: {
    borderRadius: 50,
    width: 300,
    height: 45,
    backgroundColor: "rgba(29,167,229,1)",
    justifyContent: "center",
    alignItems: "center",
  },
  buttonGoogle: {
    borderRadius: 50,
    width: 300,
    height: 45,
    backgroundColor: "rgba(182,227,163,1)",
    justifyContent: "center",
    alignItems: "center",
  },
  buttonApple: {
    // borderRadius: 50,
    width: 300,
    height: 45,
    // justifyContent: "center",
    // alignItems: "center",
  },
  containerMain: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomView: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 50,
    justifyContent: "space-around",
    alignItems: "center",
    position: "absolute",
    bottom: 50,
  },
  bottomViewFacebook: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 50,
    justifyContent: "space-around",
    alignItems: "center",
    position: "absolute",
    bottom: 160,
  },
  bottomViewGoogle: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 50,
    justifyContent: "space-around",
    alignItems: "center",
    position: "absolute",
    bottom: 105,
  },
  bottomViewApple: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    height: 50,
    justifyContent: "space-around",
    alignItems: "center",
    position: "absolute",
    bottom: 215,
  },
  textStyle: {
    color: "black",
    fontSize: 20,
    fontWeight: "bold",
  },
  textStyleSocial: {
    // fontFamily: "Helvetica Neue",
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
});
