import { StyleSheet } from "react-native";

export default StyleSheet.create({
	image: {
		flex: 1,
		resizeMode: "cover",
		justifyContent: "center",
	},
	button: {
		width: 180,
		height: 45,
		backgroundColor: "white",
		justifyContent: "center",
		alignItems: "center",
	},
	buttonFacebook: {
		width: 300,
		height: 45,
		backgroundColor: "#0000ff",
		justifyContent: "center",
		alignItems: "center",
	},
	buttonGoogle: {
		width: 300,
		height: 45,
		backgroundColor: "green",
		justifyContent: "center",
		alignItems: "center",
	},
	containerMain: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
	},
	bottomView: {
		flex: 1,
		flexDirection: "row",
		width: "100%",
		height: 50,
		justifyContent: "space-around",
		alignItems: "center",
		position: "absolute",
		bottom: 50,
	},
	bottomViewFacebook: {
		flex: 1,
		flexDirection: "row",
		width: "100%",
		height: 50,
		justifyContent: "space-around",
		alignItems: "center",
		position: "absolute",
		bottom: 105,
	},
	bottomViewGoogle: {
		flex: 1,
		flexDirection: "row",
		width: "100%",
		height: 50,
		justifyContent: "space-around",
		alignItems: "center",
		position: "absolute",
		bottom: 160,
	},
	textStyle: {
		color: "black",
		fontSize: 20,
		fontWeight: "bold",
	},
	textStyleSocial: {
		color: "white",
		fontSize: 20,
		fontWeight: "bold",
	},
});
